#!/usr/bin/env ruby
# coding: utf-8

# portions of this code are derived from
# https://github.com/cantierecreativo/bemo/blob/master/installer/install

class String
  def green
    escape 32
  end

  def yellow
    escape 33
  end

  def reset
    escape 0
  end

  def underline
    escape 4
  end

  def escape(n)
    if STDOUT.tty?
      "\033[#{n}m#{self}\033[0m"
    else
      self
    end
  end
end

def system(*args)
  abort "Command failed: #{args}" unless Kernel.system(*args)
end

def copy(url, dest)
  system 'svn', 'export', url, dest, '--force'
  puts '✓'.green + ' Written ' + dest.underline
  puts
end

def ask(question)
  print "#{'?'.yellow} #{question} [y/n] "
  answer = gets.strip.downcase
  answer == 'y' || answer == 'yes'
end

def copy_if_missing(url, dest)
  if File.exist?(dest)
    if ask("Can I overwrite #{dest.underline}?")
      copy(url, dest)
    else
      abort "Aborted."
    end
  else
    copy(url, dest)
  end
end

def name_project
  print "#{'?'.yellow} What's the name of your project? "
  dest = gets.strip.downcase
  dest
end

def copy_project
  copy_if_missing 'https://github.com/matteoscurati/midgulp/trunk', name_project
end

copy_project

puts <<DOCS

#{'Hurray!'.green} Your project has been successfully setup!

#{"Open directory's".underline} project and then the next steps:

1. Run #{'npm install'.underline}
2. Run #{'bundle install'.underline}
3. Edit #{'package.json'.underline} scripts to fit your project needs

DOCS
